-- 코드를 입력하세요
SELECT B.MEMBER_NAME, A.REVIEW_TEXT, DATE_FORMAT(A.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW A

JOIN (
    SELECT R.MEMBER_ID, M.MEMBER_NAME, RANK() OVER(ORDER BY CNT DESC) AS RANKING
    
    FROM(
        SELECT *, COUNT(MEMBER_ID) AS CNT 
        FROM REST_REVIEW 
        GROUP BY MEMBER_ID
        ) R
    
      JOIN MEMBER_PROFILE M 
      ON R.MEMBER_ID = M.MEMBER_ID
    ) B 

ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.RANKING = 1
ORDER BY A.REVIEW_DATE;